### ISSUE TITLE
The {{in-element}} helper cannot be used

### ISSUE THREAD

**Issue by MrChriZ** [kaliber5/ember-in-element-polyfill#2]
Using Ember v3.3.0 when attempting to use in-element I get the error message:
`The {{in-element}} helper cannot be used`

**Comment by simonihmig** [comment]
Thanks for reporting! Published 0.1.3 which should hopefully fix your problem!

**Comment by MrChriZ** [comment]
Magic - thanks.

I don't suppose you know of any working examples of using {{in-element}} in Ember?
My attempts so far have been less than successful and documentation out there is limited!

**Comment by simonihmig** [comment]
I used it here: 
* https://github.com/kaliber5/ember-bootstrap/blob/master/addon/templates/components/common/bs-modal.hbs#L2
* https://github.com/kybishop/ember-popper/blob/master/addon/templates/components/ember-popper.hbs#L6

(both through https://github.com/DockYard/ember-maybe-in-element, but that's basically the same, just adding the `renderInPlace` support)

Important is that the `destinationElement` exists in DOM *before* the `in-element` is rendered!

**Comment by MrChriZ** [comment]
Thanks I'll take a look at those :)

**Comment by allthesignals** [comment]
I am also seeing this. 

I have `ember-in-element-polyfill` installed in my project.

Yet, my project won't build because a dependency, [ember-mapbox-gl](https://github.com/kturney/ember-mapbox-gl), uses `in-element`, and throws this error:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: ember-mapbox-gl]) in ember-mapbox-gl/templates/components/mapbox-gl-popup.js

/Users/mattgardner/labs-zola/ember-mapbox-gl/templates/components/mapbox-gl-popup.js: Assertion Failed: The {{in-element}} helper cannot be used. ('ember-mapbox-gl/templates/components/mapbox-gl-popup.hbs' @ L1:C0) Error: /Users/mattgardner/labs-zola/ember-mapbox-gl/templates/components/mapbox-gl-popup.js: Assertion Failed: The {{in-element}} helper cannot be used. ('ember-mapbox-gl/templates/components/mapbox-gl-popup.hbs'
```

How is this happening? I have a polyfill installed that I assume enables the use of this. Yet... I get this message.

**Comment by allthesignals** [comment]
Opened an issue https://github.com/DockYard/ember-maybe-in-element/issues/61

**Comment by obrunofontana** [comment]
> Opened an issue [DockYard/ember-maybe-in-element#61](https://github.com/DockYard/ember-maybe-in-element/issues/61)

Hey dude, i was dealing with the same issue as you, what i did to resolve it was to downgrade my package-lock to the previous version,  its a workarround solution, but work for me.

**Comment by pzubar** [comment]
@obrunofontana @allthesignals I'm facing a similar issue. Could you please provide more details about downgrading? Do you mean downgrading the `ember-maybe-in-element`? What version fixes the issue? Thank you!

**Comment by Mikek2252** [comment]
@pzubar Probably too late, but it seems like it is caused by `ember-maybe-in-element: 2.1.0` adding a override or resolution to `2.0.3` fixed it for me, they dropped the polyfill in that version and seems like the app version isn't loaded in time
