### ISSUE TITLE
Error: Assertion Failed: A component or helper named "in-element" could not be found

### ISSUE THREAD

**Issue by MrChriZ** [kaliber5/ember-in-element-polyfill#4]
Thanks for your assistance the other day - I've managed to get in-element working now - so that was much appreciated.

I'm using the polyfil on on a change I'm making to the [ember-cli-photoswipe ](https://github.com/poetic/ember-cli-photoswipe) addon.

One issue I've encountered is that while the polyfill works fine in the dummy application provided with the addon; when I try to use the updated version of photoswipe in a real application the polyfill is installed but is not found.  I get the error message:
Error: Assertion Failed: A component or helper named "in-element" could not be found.

If I manually install the polyfill on the real world application then photoswipe works.
I don't understand why this is as I have the polyfill in the dependencies section of the [package.json](https://github.com/MrChriZ/ember-cli-photoswipe/blob/useInElement/package.json).
https://github.com/MrChriZ/ember-cli-photoswipe/tree/useInElement

Am I missing something obvious?

**Comment by simonihmig** [comment]
Hm, no, nothing obvious... should work, as it does for the mentioned addons that already use this. Strange, no explanation for this ATM. Which version of Ember CLI are you using (in the consuming app)?

**Comment by MrChriZ** [comment]
No difference.  Will see if I can produce a demo project

**Comment by MrChriZ** [comment]
I've created a demo project - or two effectively:
A very basic addon which includes the in-element polyfill as a dependency
https://github.com/MrChriZ/ember-inelement-test
A very basic application which imports the above addon and does not have the polyfill as a dependency:
https://github.com/MrChriZ/ember-inelement-test-consumer

The consumer application fails to launch.  Installing the polyfill resolves the problem.

**Comment by simonihmig** [comment]
Thank you @MrChriZ! Will investigate...

**Comment by MrChriZ** [comment]
Thanks.  I may have still done something silly.  I'm still rather new to the ember addon area!

**Comment by simonihmig** [comment]
@MrChriZ My apologies for letting this wait so long, I lost track of it somehow...

I checkout your reproduction repo and found the issue: in the addon you directly expose the template to the consuming app through the `app/` folder. But the usual setup for addons, and I believe the blueprint should have generated it in that way, is to have the template in `addon/` and explicitly set it as `layout` on the component, like here: https://github.com/kaliber5/ember-sticky-element/blob/master/addon/components/sticky-element.js#L7 You then also need to move `ember-cli-htmlbars` to `dependencies`. 

With those changes it should work, as I quickly confirmed with your test addon. It seems the AST transform that this addons adds will not run on the addon's templates when being put in `app/` directly. Not sure why, and if this should be considered a bug of Ember CLI or whatever. But at least nothing I can change as part of this addon, AFAIK!
